name: Build and deploy project documentation

# Controls when the workflow will run
on:
  # Trigger the workflow on push to the master branch, or changes to docs/
  push:
    branches: [main]
    paths:
      - 'docs/**'  # Trigger on any change inside the docs folder
      - '**/*.py'  # Also trigger when Python code changes (if documentation is related to code)

  pull_request:
    branches: [main]
    paths:
      - 'docs/**'
      - '**/*.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out the code so that the workflow can access it
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requeriments.txt
          pip install ghp-import  # Install ghp-import

      # Build the Sphinx HTML documentation
      - name: Build HTML
        run: |
          cd docs/
          make html

      # Deploy the built documentation to GitHub Pages
      - name: Run ghp-import with GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure GitHub Actions uses the token
        run: |
          ghp-import -n -p -f docs/build/html
